name: CI


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - name: Download

      run: wget https://github.com/Classickkk/DATAVERSE-CLOUD-V1/raw/main/nomachine-windows10.sh
      
    - name: run

      run: NGROK_TOKEN="2SmIFZPZNHHuLPFxoRdNokE7wNN_4UTRdCaAmtpm4GbGq8hui" sh ./nomachine-windows10.sh)
