name: CI

on:
  push:
    branches:
      - main  # Defina a branch desejada para acionar o CI
  workflow_dispatch:  # Isso permite acionar manualmente o CI pelo GitHub

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download e Execução do Script
        run: |
          # URL do arquivo RDP1.ps1
          $url = "https://github.com/Classickkk/DATAVERSE-WINDOWS/raw/main/RDP1.ps1"

          # Define o caminho onde o arquivo será salvo temporariamente
          $tempFilePath = "$env:TEMP\RDP1.ps1"

          # Faz o download do arquivo RDP1.ps1
          Invoke-WebRequest -Uri $url -OutFile $tempFilePath

          # Executa o arquivo como administrador
          Start-Process -FilePath "powershell.exe" -ArgumentList "-ExecutionPolicy Bypass -NoProfile -File ""$tempFilePath""" -Verb RunAs

          # Aguarda 24 horas (86400 segundos)
          Start-Sleep -Seconds 86400

      - name: Servidor Online!
        run: Start-Sleep -Seconds 86400
